main: Creadores.ninjacr.Emotions.Main
name: Emotions
authors: [NinjaCR & Trollhunters501]
description: "Expresa Tus sentimientos!"
website: "https://github.com/Trollhunters501/Nukkit-Emotions"
version: "1.0"
api: ["1.0.0"]
load: POSTWORLD





